# Generated by Django 4.2.4 on 2023-11-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
                ("image_cover_url", models.URLField()),
                ("price", models.IntegerField()),
                ("publisher", models.CharField(max_length=100)),
                ("Description", models.TextField(blank=True)),
            ],
        ),
    ]
