# Generated by Django 4.2.4 on 2023-12-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_gameitem_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="digital",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
