# Generated by Django 4.2.7 on 2023-12-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
