# Generated by Django 4.2.7 on 2023-12-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_game_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
