# Generated by Django 4.2.9 on 2024-01-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0009_game_downloads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="downloads",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
