# Generated by Django 4.2.4 on 2023-11-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_rename_userprofile_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="images/profiles/default.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
