# Generated by Django 4.2.4 on 2023-11-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profiles/user-default.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
