# Generated by Django 4.2.4 on 2023-12-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_rename_purchasehistory_userpurchasehistory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="permenant_address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="state",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="temporary_address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="zipcode",
        ),
    ]
