# Generated by Django 4.2.7 on 2023-12-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
    ]
